let users = [
	{
		name: 'Frank Jens',
		email: 'frankjens@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Sigmunde Arafad',
		email: 'sigmundekoehler@test.de',
		password: '123789',
		colorIndex: '',
	},
	{
		name: 'Gertraut Harald',
		email: 'gertrautharald@test.de',
		password: '123456dfgh789',
		colorIndex: '',
	},
	{
		name: 'Klaudia Bumsbine',
		email: 'klaudiaschoenfeld@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Peter Lustig',
		email: 'Peterlustig@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Peter Klausen',
		email: 'PeterKlausen@test.de',
		password: '123456789',
		colorIndex: '',
	},
    {
		name: 'Charlotte Grupper',
		email: 'charlottegrupper@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Jens Jensen',
		email: 'jensjensen@test.de',
		password: '123789',
		colorIndex: '',
	},
	{
		name: 'Jonny Depp',
		email: 'jonnydepp@test.de',
		password: '123456dfgh789',
		colorIndex: '',
	},
	{
		name: 'Abdul Hans',
		email: 'abdulhans@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Xava Schreiner',
		email: 'xavaschreiner@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Jorginia Klaus',
		email: 'jorginiaklaus@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Claudia Schiffer',
		email: 'warmaljung@web.de',
		password: '123',
		colorIndex: '',
	},
	{
		name: 'Basti H',
		email: 'bastih@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Stefan B',
		email: 'stefanb@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Christian G',
		email: 'christiang@test.de',
		password: '123456789',
		colorIndex: '',
	},
	{
		name: 'Dorian J',
		email: 'dorianj@web.de',
		password: '123',
		colorIndex: '',
	},

];
