let users = [
	{
		name: 'Frank Jens',
		email: 'frankjens@test.de',
		password: '123456789',
		colorIndex: '4',
		firstSecondLetter: 'FJ',
	},
	{
		name: 'Sigmunde Arafad',
		email: 'sigmundekoehler@test.de',
		password: '123789',
		colorIndex: '8',
		firstSecondLetter: 'SA',
	},
	{
		name: 'Gertraut Harald',
		email: 'gertrautharald@test.de',
		password: '123456dfgh789',
		colorIndex: '3',
		firstSecondLetter: 'GH',
	},
	{
		name: 'Klaudia Bumsbine',
		email: 'klaudiaschoenfeld@test.de',
		password: '123456789',
		colorIndex: '1',
		firstSecondLetter: 'KB',
	},
	{
		name: 'Peter Lustig',
		email: 'Peterlustig@test.de',
		password: '123456789',
		colorIndex: '6',
		firstSecondLetter: 'PL',
	},
	{
		name: 'Peter Klausen',
		email: 'PeterKlausen@test.de',
		password: '123456789',
		colorIndex: '5',
		firstSecondLetter: 'PK',
	},
	{
		name: 'Charlotte Grupper',
		email: 'charlottegrupper@test.de',
		password: '123456789',
		colorIndex: '8',
		firstSecondLetter: 'CG',
	},
	{
		name: 'Jens Jensen',
		email: 'jensjensen@test.de',
		password: '123789',
		colorIndex: '8',
		firstSecondLetter: 'JJ',
	},
	{
		name: 'Jonny Depp',
		email: 'jonnydepp@test.de',
		password: '123456dfgh789',
		colorIndex: '2',
		firstSecondLetter: 'JD',
	},
	{
		name: 'Abdul Hans',
		email: 'abdulhans@test.de',
		password: '123456789',
		colorIndex: '7',
		firstSecondLetter: 'AH',
	},
	{
		name: 'Xava Schreiner',
		email: 'xavaschreiner@test.de',
		password: '123456789',
		colorIndex: '1',
		firstSecondLetter: 'XS',
	},
	{
		name: 'Jorginia Klaus',
		email: 'jorginiaklaus@test.de',
		password: '123456789',
		colorIndex: '9',
		firstSecondLetter: 'JK',
	},
	{
		name: 'Claudia Schiffer',
		email: 'warmaljung@web.de',
		password: '123',
		colorIndex: '0',
		firstSecondLetter: 'CS',
	},
	{
		name: 'Basti H',
		email: 'bastih@test.de',
		password: '123456789',
		colorIndex: '8',
		firstSecondLetter: 'BH',
	},
	{
		name: 'Stefan B',
		email: 'stefanb@test.de',
		password: '123456789',
		colorIndex: '9',
		firstSecondLetter: 'SB',
	},
	{
		name: 'Christian G',
		email: 'christiang@test.de',
		password: '123456789',
		colorIndex: '8',
		firstSecondLetter: 'CG',
	},
	{
		name: 'Dorian J',
		email: 'dorianj@web.de',
		password: '123',
		colorIndex: '2',
		firstSecondLetter: 'DJ',
	},

];
